name: Example Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Use secret as environment variable
      run: echo "Secret is ${{ secrets.DATABASE_PASSWORD }}"
